blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blogapp.urls', namespace='blogapp')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blogapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
   url(r'^$', views.IndexView.as_view(), name="index"),
   url(r'^(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
   url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryDetailView.as_view(), name="categorydetail"),
]

blogapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    picture = models.ImageField(upload_to="pics/%Y/%m/%d", blank=True, null=True)
    pub_date = models.DateTimeField()
    category = models.ManyToManyField('Category', blank=True, null=True)
    keywords = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    person = models.CharField(max_length=200)
    comment_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return "%s - %s" % (self.person, self.comment_text[:50])

class Category(models.Model):
    category_name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "categories"

    def __unicode__(self):
        return self.category_name

blogapp/views.py
from django.shortcuts import render
from django.views import generic

from .models import Post, Comment, Category

class IndexView(generic.ListView):
    template_name = 'blogapp/index.html'
    model = Post

    def get_queryset(self):
        #SELECT * from blogapp_post ORDER BY pub_date DESC LIMIT 5
        return Post.objects.order_by('-pub_date')[:5]


class PostDetailView(generic.DetailView):
    model = Post

#     def get_context_data(self, *args, **kwargs):
#         context = super(PostDetailView,self).get_context_data()
#         context.update({"comment_list": self.get_object().comment_set.all()})
#         context.update({"comment_list": Comment.objects.filter(post__pk = self.kwargs.get('pk'))})
#         return context;

class CategoryDetailView(generic.DetailView):
    model = Category
    # query set

















































# # Create your views here.
# class PostDetail(DetailView):
#     model = Post
# 
#     def get_context_data(self):
#         context = super(PostDetail,self).get_context_data()
#         context.update({"form": CommentForm()})
#         return context;

blogapp/templates/blogapp/_post.html
{% load thumbnail %}

        {% if post.picture %}
            {% thumbnail post.picture "300x300" crop="center" as im %}
            <img src="{{ im.url }}" style="text-align: center;">
            {% endthumbnail %}
        {% endif %} {# End post.picture #}
        <a href="{% url 'blogapp:detail' post.id %}"><h2>{{ post.title }}</h2></a><br/>
        <h4 class="published">
            Published {{ post.pub_date|date:"M d, Y" }}
            (Filed in: 
            {% for category in post.category.all %}
                <a href="{% url 'blogapp:categorydetail' category.id %}" >{{ category.category_name }}</a>
            {% empty %}
                No categories
            {% endfor %}
            )
        </h4>
        <div class="post-body">
        {{ post.body }}
        </div>

blogapp/templates/blogapp/category_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block 'title' %}{{ category.category_name }}{% endblock 'title' %}

{% block 'content' %}

	{% for post in category.post_set.all %}
		{% include 'blogapp/_post.html' %}
	{% endfor %}

{% endblock 'content' %}

blogapp/templates/blogapp/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block 'title' %}Most Recent Blog Posts{% endblock 'title' %}


{% block 'content' %}
<h1>Most Recent Blog Posts</h1>

{% if post_list %}
   
   {% for post in post_list %}


        {% include 'blogapp/_post.html' %}


        <a href="{% url 'blogapp:detail' post.id %}#comment-section">Leave a comment...</a>

        {% if not forloop.last %}
            <hr>
        {% endif %}

   {% endfor %}

   
{% else %}
    <p>Sorry folks. No posts to show.</p>

{% endif %}

{% endblock 'content' %}


 

blogapp/templates/blogapp/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block 'title' %}{{ post.title }}{% endblock 'title' %}


{% block 'content' %}

        {% include 'blogapp/_post.html' %}

    <!-- Comments go here -->
    {% for comment in post.comment_set.all reversed %}

        <h4>On {{ comment.pub_date|date:"M d, Y h:m:s" }}, {{ comment.person }} commented:</h4>
        <div class="well">
        {{ comment.comment_text }}
        </div>

        {% if not forloop.last %}
        <hr>
        {% endif %}

    {% empty %}
        <p>Be the first of your friends to comment on this post.</p>

    {% endfor %}

{% endblock 'content' %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block 'title' %}Max's Adventure Blog{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <link rel="stylesheet" href="/media/style.css">
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Max's Adventure Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/admin/">Admin</a></li>
            <li><a href="mailto:d00241719@dmail.dixie.edu">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="margin-top: 50px;">
{% block 'content' %}

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>